server:
  port: 8989
spring:
  datasource:
    username: # 用户名
    password: # 密码
    url: # 数据库连接地址
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
  servlet:
      multipart:
        enabled: true #是否启用http上传处理
        max-request-size: 1000MB #最大请求文件的大小
        max-file-size: 200MB #设置单个文件最大长度
        file-size-threshold: 200MB #当文件达到多少时进行磁盘写入
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.coderman.common.model
  configuration:
    map-underscore-to-camel-case: true
files:
  access-key: # 密钥
  secret-key: # key
  endpoint: # 地域
  bucket: # 桶
  domain: # 域名，末尾一定要带有 /
